name: Deploy do Site no GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Atualizado de v3 para v4

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Atualizado de v3 para v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Corrigir permissões (chmod)
        run: chmod +x ./node_modules/.bin/react-scripts

      - name: Buildar o projeto
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4 # Atualizado de v3 para v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # Atualizado de v2 para v3 (Esta é a correção principal)
        with:
          path: './build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Atualizado de v2 para v4